// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Contextual help topics for the console info panel (§12.6). Copy is the
// ratified content bundle (docs/v42-console-improvements/help-content-bundle.md);
// anchors match SECTION_IDS / detail-tab ids per content-map.md. Bold spans use
// **markdown** and are rendered by HelpPanelContent.
//
// Traffic-shape mode names and definitions come from @amzn/dlt-common/traffic-shape
// rather than being written here, so the info panel says the same thing as the
// create form, the CLI, and the MCP server. The panel takes the medium tier; the
// long tier is reserved for the Implementation Guide.

import { TRAFFIC_SHAPE_LABELS, TRAFFIC_SHAPE_MEDIUM_DEFINITIONS } from "@amzn/dlt-common/traffic-shape";

export interface HelpTopic {
  id: string;
  title: string;
  /** Body copy. Lines starting with "- " render as list items; **bold** is honored. */
  content: string;
  learnMoreUrl: string;
  learnMoreLabel: string;
  /** Extra learn-more links rendered after the primary one, for topics the bundle gives more than one. */
  learnMoreLinks?: { url: string; label: string }[];
}

export const helpTopics: Record<string, HelpTopic> = {
  "test-configuration": {
    id: "test-configuration",
    title: "Test Configuration",
    content:
      "Name and describe your test scenario. The name identifies the scenario in the scenarios list, dashboards, and results, so choose something your team recognizes later — for example, the service and traffic pattern under test (checkout-api-peak).\n\n" +
      "- **Name** — required. Displayed everywhere the scenario appears in the console and results.\n" +
      "- **Description** — optional but recommended. Capture intent (what you are testing and why) so results are interpretable months later.\n" +
      "- **Keywords** — short text labels (up to 5) for organizing and filtering scenarios. See the Keywords help topic.\n" +
      "- **Healthy threshold** — the percentage of tasks that must remain healthy for the test to continue, evaluated per Region (integer 0–100, default 90). If healthy tasks in a Region fall below the threshold, DLT terminates the run rather than reporting results generated by degraded load.\n\n" +
      "Changes here do not affect a running test; they apply from the next run.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html",
    learnMoreLabel: "Create a test scenario",
  },
  tags: {
    id: "tags",
    title: "Keywords",
    content:
      "Short text labels attached to the scenario — up to 5 keywords of 50 characters each. Use them to group and filter scenarios in the list view by team, service, environment, or campaign (payments, staging, black-friday).\n\n" +
      "Keywords are DLT scenario metadata: they organize scenarios in the console and are searchable in the scenarios list. They are simple labels, not key-value pairs, are not applied as AWS resource tags on the underlying infrastructure, and do not affect test execution.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html",
    learnMoreLabel: "Create a test scenario",
  },
  "test-type": {
    id: "test-type",
    title: "Test type",
    content:
      "Choose how the load is defined.\n\n" +
      "- **Simple HTTP Endpoint** — no script required. DLT generates the load against one URL you configure below. Best for quick capacity checks.\n" +
      "- **JMeter** — upload a JMeter test plan (.jmx, or a zip containing it with supporting files). Broadest protocol coverage. The console shows the bundled JMeter version and its supported plugins.\n" +
      "- **K6** — upload a k6 script (JavaScript). Strong for modern web protocols; requires acknowledging the k6 license terms.\n" +
      "- **Locust** — upload a Locust file (Python). Any Python library your test needs can be included via the zip.\n\n" +
      "The framework version bundled with this deployment is shown in the info alert for each type; version-specific behaviors and security notes link from there. Zips must place supporting files relative to the script path shown in the example layout.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html",
    learnMoreLabel: "Create a test scenario",
  },
  "traffic-shape": {
    id: "traffic-shape",
    title: "Traffic shape",
    content:
      "Choose who defines the traffic shape. Native is available for script-based tests (JMeter, K6, Locust); the Simple HTTP Endpoint type always uses Standard.\n\n" +
      `**${TRAFFIC_SHAPE_LABELS.standard}** — ${TRAFFIC_SHAPE_MEDIUM_DEFINITIONS.standard}\n\n` +
      `**${TRAFFIC_SHAPE_LABELS.native}** — ${TRAFFIC_SHAPE_MEDIUM_DEFINITIONS.native}\n\n` +
      `Switching to ${TRAFFIC_SHAPE_LABELS.native} replaces Concurrency and Ramp Up / Hold For with Task Count and a safety duration.`,
    learnMoreUrl:
      "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html#step-3-traffic-shape",
    learnMoreLabel: "Create a test scenario",
  },
  "http-endpoint": {
    id: "http-endpoint",
    title: "HTTP endpoint",
    content:
      "For Simple HTTP Endpoint tests, define the request every virtual user sends.\n\n" +
      "- **Target URL** — the endpoint under test. Ensure it is reachable from the selected AWS Regions and that you are authorized to load test it.\n" +
      "- **Method** — GET, POST, PUT, or DELETE.\n" +
      "- **Custom headers** — added to every request. Use for authorization tokens, content-type, or trace headers that mark traffic as synthetic.\n" +
      "- **Body** — request payload for POST/PUT.\n\n" +
      "Every virtual user in every task sends this same request in a loop for the test duration. Response times, throughput, and errors are aggregated in the results.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html",
    learnMoreLabel: "Create a test scenario",
  },
  "file-upload": {
    id: "file-upload",
    title: "Upload test script",
    content:
      "Upload the script or bundle for the selected framework: a single script file, or a zip when the test needs supporting files (data files, plugins, modules).\n\n" +
      "In a zip, the script path is relative to the zip root — follow the example layout shown for the selected test type. The uploaded bundle is stored with the scenario and shipped to every Fargate task at run time; all regions in a multi-region test run the same bundle.\n\n" +
      "In Native mode, set a **Safety duration** here. Your script defines its own load, so this cap is a guard against a script that never exits rather than a schedule. If the test is still running when the cap elapses, DLT stops the framework, collects the results for the portion that ran, and records the run as completed (default 4 hours, maximum 24 hours).\n\n" +
      "Replacing the file affects the next run, not any test currently executing.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/create-test-scenario.html",
    learnMoreLabel: "Create a test scenario",
  },
  "multi-region": {
    id: "multi-region",
    title: "Multi-Region traffic configuration",
    content:
      "Select the Regions that generate load and size the traffic per Region. Total load = tasks × virtual users, summed across Regions.\n\n" +
      "- **Task Limit / Available** — read-only Fargate capacity per Region: the account's task ceiling and how many tasks you can launch right now. See Task availability info for details.\n" +
      "- **Tasks** — Fargate containers launched in that Region (minimum 1). Each task consumes vCPU capacity and one IP address per configured subnet; keep it within the Available count above.\n" +
      "- **Traffic (virtual users)** — virtual users per task (minimum 1). Per-Region virtual users = tasks × virtual users. In Native mode this is read-only — your uploaded script sets the virtual users, and each task runs a full copy of it.\n\n" +
      "Values above the recommended thresholds (2,000 tasks or 200 virtual users per task) trigger a warning: they can work, but validate that your per-task resources sustain the user count — a container starved for CPU under-generates load and skews results.\n\n" +
      "Distributing load across Regions tests geographic latency effects and raises total capacity beyond a single Region's limits.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/multi-region-deployment.html",
    learnMoreLabel: "Multi-Region deployment",
  },
  "regional-availability": {
    id: "regional-availability",
    title: "Regional task availability",
    content:
      "Current Fargate capacity per Region, so you can size task counts against real headroom.\n\n" +
      "- **vCPUs per task** — vCPUs each DLT task consumes.\n" +
      "- **DLT task limit** — the theoretical task ceiling: the account's Fargate vCPU quota in that Region divided by vCPUs per task.\n" +
      "- **Available DLT tasks** — what you can launch right now: (quota − vCPUs currently in use) ÷ vCPUs per task. Other running tests and any other Fargate workloads in the account reduce this number.\n\n" +
      "Figures are fetched live from your account's quotas and usage. If a Region shows fewer available tasks than your test needs, lower the task count, wait for running work to finish, or request a Fargate quota increase.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/quotas.html",
    learnMoreLabel: "Quotas",
  },
  "test-duration": {
    id: "test-duration",
    title: "Test duration",
    content:
      "Shape the load over time. These settings apply to Standard mode only; in Native mode your script owns the ramp and hold, and you set a safety duration instead.\n\n" +
      "- **Ramp up** — time to climb from zero to the full virtual user count (minimum 0). A gradual ramp reveals the load level where behavior degrades; an instant ramp (0) tests spike response, like a flash sale or failover.\n" +
      "- **Hold for** — time to sustain the full load (minimum 1). Size this to reach steady state: long enough for caches to warm, autoscaling to react, and percentile metrics to stabilize.\n\n" +
      "Total test time is ramp up + hold for, plus provisioning and results parsing around it. Results are most comparable across runs (and against a baseline) when duration settings match.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/run-test-scenario.html",
    learnMoreLabel: "Run a test scenario",
  },
  schedule: {
    id: "schedule",
    title: "Schedule",
    content:
      "Choose when the test runs.\n\n" +
      "- **Run now** — the test starts as soon as you create or run the scenario.\n" +
      "- **Run on schedule** — the test runs automatically on a recurring cron expression. Provide the five cron fields (minutes, hours, day of month, month, day of week); the console validates the expression and shows the next run time before you save.\n\n" +
      "A scheduled scenario shows status **Scheduled** until its next trigger. Each scheduled execution consumes Fargate capacity like any other run, so verify regional availability supports your task count at the scheduled time — other tests may be running then.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/run-test-scenario.html",
    learnMoreLabel: "Run a test scenario",
  },
  results: {
    id: "results",
    title: "Test run results",
    content:
      "Aggregated performance metrics for this run: request volume, success and error counts, response-time percentiles, and throughput.\n\n" +
      "- **Views** — Overall (all endpoints aggregated), By Endpoint, and By Region. Select a row to load its detailed dashboard: volume, performance (average response time, latency, connection time), and throughput (requests per second, bandwidth).\n" +
      "- **Percentiles** — p0 through p100 response times per endpoint. Watch the high percentiles (p95/p99); averages hide tail latency, and the tail is what your slowest users experience.\n" +
      "- **Baseline comparison** — when the scenario has a baseline run set, each metric shows its delta against the baseline (actual values or percentage). Use it to catch regressions between releases. Set a baseline from the scenario's Test Runs tab; comparisons are most meaningful when both runs used the same load profile.\n\n" +
      "Results appear after the run completes and parsing finishes. For a failed run, check the Errors tab, then consider sending the run to an investigation (Investigations tab).",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/explore-test-results.html",
    learnMoreLabel: "Explore test results",
  },
  errors: {
    id: "errors",
    title: "Errors",
    content:
      "Failed requests from this run, broken down by error type and response code.\n\n" +
      "Use this tab to distinguish application errors (HTTP 4xx/5xx returned by the target) from connection-level failures (timeouts, refused connections), which often indicate the target saturated or a network path failed under load. An empty tab means all requests succeeded.\n\n" +
      "Error counts here match the failure totals on the Results tab. For raw framework logs behind a failure, check the Artifacts tab (read .err files first).",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/explore-test-results.html",
    learnMoreLabel: "Explore test results",
  },
  artifacts: {
    id: "artifacts",
    title: "Artifacts",
    content:
      "Raw files produced by the test run, stored in the solution's S3 bucket: framework execution logs, error output, and result files from each task.\n\n" +
      "The tab shows the bucket, prefix, and a browsable file list with downloads. When diagnosing a failed run, start with the .err files — they carry the framework's failure details. When you send a run to a DevOps Agent investigation, DLT automatically uploads the priority artifacts (error logs, stdout, execution logs) to the agent space so the agent works from the same logs.\n\n" +
      "Artifacts persist in S3 after the run per the bucket's lifecycle settings, so links remain usable for post-hoc analysis.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/explore-test-results.html",
    learnMoreLabel: "Explore test results",
  },
  investigations: {
    id: "investigations",
    title: "Investigations",
    content:
      "Hand this test run to an AWS DevOps Agent for root-cause analysis. Available in deployments with a registered agent space (see Agent Integration).\n\n" +
      "**Send to agent** packages the run's results — load profile, metrics, baseline comparison if set, plus an automatic upload of the run's test artifacts — into a structured investigation request. You can add free-text context (what changed, what to focus on) and set a priority. The investigation then runs inside the DevOps Agent; this tab tracks its status and shows findings when complete.\n\n" +
      "The handoff is one-way: DLT initiates the investigation and displays its findings. Remediation happens in the DevOps Agent; to confirm a fix, re-run the test and compare against the baseline. An investigation cannot be restarted — send a new one instead.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/devops-agent-integration.html",
    learnMoreLabel: "AWS DevOps Agent integration",
  },
  "agent-integration": {
    id: "agent-integration",
    title: "Agent integration",
    content:
      "Connect AI agents to this DLT deployment.\n\n" +
      "- **MCP endpoint** — the deployment's Model Context Protocol server URL. Point any MCP-compatible agent or IDE at it to query scenarios, runs, and results. Shown only when the stack was deployed with DeployMCPServer enabled; otherwise redeploy with that parameter set.\n" +
      "- **Agent spaces** — registered AWS DevOps Agent connections, used by the Investigations feature on test runs. Register a space with its ARN and test the connection before saving. Two requirements: the agent space must belong to the same AWS account as this deployment (a different Region in the account is supported), and the agent space must carry the resource tag dlt-integration=allowed in the DevOps Agent. The tag is applied by the Agent Space administrator and confirms both sides consent to the integration; without it, the connection test fails with an access-denied error.\n" +
      "- **Connections** — manage or remove existing agent spaces. Removing a space stops new investigations to it; completed investigation findings remain viewable.",
    learnMoreUrl: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/mcp-server-integration.html",
    learnMoreLabel: "MCP Server integration",
    learnMoreLinks: [
      {
        url: "https://docs.aws.amazon.com/solutions/latest/distributed-load-testing-on-aws/devops-agent-integration.html",
        label: "AWS DevOps Agent integration",
      },
    ],
  },
};
