// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import ReactDOM from "react-dom/client";
import { Amplify, ResourcesConfig } from "aws-amplify";
import "./styles.css";
import { Provider } from "react-redux";
import { setupStore } from "./store/store.ts";
import { App } from "./App.tsx";
import { NotificationContextProvider } from "./contexts/NotificationContext.tsx";
import { UserContextProvider } from "./contexts/UserContext.tsx";
import React from "react";
import { BrowserRouter } from "react-router-dom";
import { startMockServer } from "./mocks/browser.ts";

/**
 * Read the configuration .json file that was generated by the custom resource during deployment.
 * If running in development mode, also enable mock-service-worker to intercept defined http requests.
 */
const getRuntimeConfig = async () => {
  let runtimeConfig: any = {};
  try {
    const response = await fetch("/aws-exports.json");
    runtimeConfig = await response.json();
  } catch (e) {
    console.log(e);
  }
  // Only start mock server if we don't have a real API endpoint
  const hasRealApi = runtimeConfig.ApiEndpoint;
  if (process.env.NODE_ENV === "development" && !hasRealApi) {
    console.log("Starting mock server because no real API endpoint found");
    await startMockServer(runtimeConfig.ApiEndpoint);
  }
  return runtimeConfig;
};

getRuntimeConfig().then((json) => {
  const awsconfig: ResourcesConfig = {
    Auth: {
      Cognito: {
        userPoolId: json.UserPoolId,
        userPoolClientId: json.PoolClientId,
        identityPoolId: json.IdentityPoolId,
      },
    },
    API: {
      REST: {
        "solution-api": {
          endpoint: json.ApiEndpoint,
        },
      },
    },
    Storage: {
      S3: {
        bucket: json.UserFilesBucket,
        region: json.UserFilesBucketRegion,
      },
    },
  };
  Amplify.configure(awsconfig);

  const store = setupStore();
  const root = ReactDOM.createRoot(document.getElementById("root") as HTMLElement);
  root.render(
    <React.StrictMode>
      <BrowserRouter>
        <Provider store={store}>
          <UserContextProvider>
            <NotificationContextProvider>
              <App />
            </NotificationContextProvider>
          </UserContextProvider>
        </Provider>
      </BrowserRouter>
    </React.StrictMode>
  );
});
