// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import ReactDOM from "react-dom/client";
import { Amplify, ResourcesConfig } from "aws-amplify";
import "./styles.css";
import { Provider } from "react-redux";
import { setupStore } from "./store/store.ts";
import { App } from "./App.tsx";
import { NotificationContextProvider } from "./contexts/NotificationContext.tsx";
import { UserContextProvider } from "./contexts/UserContext.tsx";
import React from "react";
import { BrowserRouter } from "react-router-dom";
import { startMockServer } from "./mocks/browser.ts";

/**
 * Read the configuration .json file that was generated by the custom resource during deployment.
 * If running in development mode, also enable mock-service-worker to intercept defined http requests.
 */
const getRuntimeConfig = async () => {
  let runtimeConfig: any = {};
  try {
    const response = await fetch("/aws-exports.json");
    runtimeConfig = await response.json();
  } catch (e) {
    console.log(e);
  }
  // Only start mock server if we don't have a real API endpoint
  const hasRealApi = runtimeConfig.ApiEndpoint;
  if (process.env.NODE_ENV === "development" && !hasRealApi) {
    console.log("Starting mock server because no real API endpoint found");
    await startMockServer(runtimeConfig.ApiEndpoint);
  }
  return runtimeConfig;
};

/**
 * One-time migration: clear stale Amplify auth data from localStorage that was
 * stored by the previous sign-in method (withAuthenticator / USER_SRP_AUTH).
 *
 * When upgrading to the Cognito Hosted UI (OAuth/PKCE), leftover tokens and
 * user data from the old flow can confuse Amplify's auth state machine, causing
 * the first post-upgrade sign-in to hang on the redirect callback.
 *
 * IMPORTANT: This must NOT run when the page is an OAuth callback (URL has ?code=
 * or ?state= params), because the new OAuth/PKCE flow also stores its code_verifier
 * under CognitoIdentityServiceProvider.* keys. Clearing those would break the
 * token exchange.
 */
const MIGRATION_FLAG = "dlt-auth-migrated-to-hosted-ui";

const clearLegacyAuthDataIfNeeded = () => {
  // Already migrated — nothing to do.
  if (localStorage.getItem(MIGRATION_FLAG)) {
    return;
  }

  // If this is an OAuth callback page load, do NOT clear localStorage now.
  // The PKCE code_verifier stored before the redirect lives under the same
  // CognitoIdentityServiceProvider.* prefix and must survive this load.
  const params = new URLSearchParams(window.location.search);
  if (params.has("code") || params.has("state")) {
    return;
  }

  // Clear legacy keys from the old withAuthenticator (USER_SRP_AUTH) flow.
  const legacyKeys = Object.keys(localStorage).filter(
    (key) =>
      key.startsWith("CognitoIdentityServiceProvider.") ||
      key.startsWith("amplify-signin-with-hostedUI")
  );
  if (legacyKeys.length > 0) {
    console.log("One-time migration: clearing legacy auth data from localStorage:", legacyKeys);
    legacyKeys.forEach((key) => localStorage.removeItem(key));
  }

  // Mark migration as complete so this never runs again.
  localStorage.setItem(MIGRATION_FLAG, "true");
};

getRuntimeConfig().then((json) => {
  // One-time: remove auth state left over from the previous (non-OAuth) sign-in
  // method before configuring Amplify, so the new OAuth flow starts cleanly.
  clearLegacyAuthDataIfNeeded();

  const awsconfig: ResourcesConfig = {
    Auth: {
      Cognito: {
        userPoolId: json.UserPoolId,
        userPoolClientId: json.PoolClientId,
        identityPoolId: json.IdentityPoolId,
        loginWith: {
          oauth: {
            domain: json.UserPoolDomain,
            scopes: ["openid", "email", "profile"],
            redirectSignIn: [window.location.origin],
            redirectSignOut: [window.location.origin],
            responseType: "code",
          },
        },
      },
    },
    API: {
      REST: {
        "solution-api": {
          endpoint: json.ApiEndpoint,
        },
      },
    },
    Storage: {
      S3: {
        bucket: json.UserFilesBucket,
        region: json.UserFilesBucketRegion,
      },
    },
  };
  Amplify.configure(awsconfig);

  const store = setupStore();
  const root = ReactDOM.createRoot(document.getElementById("root") as HTMLElement);
  root.render(
    <React.StrictMode>
      <BrowserRouter>
        <Provider store={store}>
          <UserContextProvider>
            <NotificationContextProvider>
              <App />
            </NotificationContextProvider>
          </UserContextProvider>
        </Provider>
      </BrowserRouter>
    </React.StrictMode>
  );
});
